dist: trusty
sudo: required

language: python
python:
    - "3.5"
    - "3.6"
install:
  - pip install -r requirements.txt
script:
    - coverage run -m unittest
after_success:
    - codeclimate-test-reporter
