dist: trusty
sudo: required

language: python
python:
    - "3.5"
    - "3.6"
install:
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update -qq
  - sudo apt-get install -y libsodium13
  - pip install -r requirements.txt
script:
    - python -m unittest
